### ISSUE TITLE
water mask ortho model failing in barrier island environments

### ISSUE THREAD

**Issue by xandra22** [Doodleverse/segmentation_zoo#12]
Hello,

I applied the "ortho_6410157" model to some barrier island plane imagery, and the results were not accurate enough to be useful for my work. I have a powerpoint of example images and overlays to provide examples of where the model worked well and failed, and I ran the model using both the "ensemble" and "best" options for comparison. 
[Examples of NorthCore Water Masked Images.pptx](https://github.com/Doodleverse/segmentation_zoo/files/8892618/Examples.of.NorthCore.Water.Masked.Images.pptx)

Here are a handful of example images from my dataset:
![NOAA_NGS_NorthCore_2019_10000_78000](https://user-images.githubusercontent.com/98843496/173395458-ea9c91d5-7f70-4ee7-87e1-8f14d7a4b938.jpg)
![NOAA_NGS_NorthCore_2019_14000_74000](https://user-images.githubusercontent.com/98843496/173395469-fabcff05-45e3-4373-ab43-503a3e49d030.jpg)
![NOAA_NGS_NorthCore_2019_14000_72000](https://user-images.githubusercontent.com/98843496/173395484-8bd4af06-cb81-42d7-9e02-7bd07021bfdf.jpg)
![NOAA_NGS_NorthCore_2019_18000_72000](https://user-images.githubusercontent.com/98843496/173395501-62dae36f-1679-464f-8240-b1adf98d36e4.jpg)
![NOAA_NGS_NorthCore_2019_66000_26000](https://user-images.githubusercontent.com/98843496/173395817-192fe352-33da-406a-bb95-3c2ccf3a887b.jpg)

I was wondering if I could improve the results without training a new model? Our project is currently labeling these images in doodler for habitat mapping work, so we'll have those doodled images for future model training on top of coasttrain and other available datasets, but I didn't know if there were ways to try to improve the results in the meantime. 

Also, a side note: I had trouble installing the environment via conda. It worked for me when I went through the list of libraries and installed them via pip, starting with scikit-image. Unsure why, but I figured I'd share my environment woes while I'm asking about the model.

Thanks!
Xandra

**Comment by dbuscombe-usgs** [comment]
Hi @xandra22 :wave: 

Thanks a lot for trying this - despite not being as accurate as we'd both like, this is very valuable feedback for me. It is useful to know how much error to expect when we apply this Coast Train derived model to arbitrary data. Clearly, marshes are an issue, probably because we have relatively few example marshes in the training data. 

If you have good label images for some of your marshes (I know doodler has been an issue - will respond to those issues), I could incorporate them into the next model retraining

Also, I will likely look at implementation using your example images to see if any insight can be made. In the meantime, I am providing another set of weights for a model trained on SWED data. This is preliminary and should not yet be shared  (just for testing, work in progress). The zipped folder contains a set of weights and a config file. It is targeted to smaller tiles (SWED data are 256x256x3 rgb pixels), but it'd be nice to know if this model trained on SWED is any better. In theory it should be, because it has seen more data from marshes, however all the imagery used in training and model validation is 10m sentinel imagery

[swed_water_rgb_256_v2.zip](https://github.com/Doodleverse/segmentation_zoo/files/8901213/swed_water_rgb_256_v2.zip)

**Comment by dbuscombe-usgs** [comment]
I'm going to close this now because we have new models to test. @xandra22 feel free to reopen this if you want to try testing the new models. Otherwise, we'll coordinate in RSCC meetings, etc
